import { packageOf, currentModulePath, patch, findFile } from '@tech_query/node-toolkit';

import { basename, resolve, join, extname } from 'path';

import {
    ensureDirSync, copy, readdirSync, readJSON, outputJSON, remove, outputFile
} from 'fs-extra';

import Git from 'simple-git/promise';

import spawn from 'cross-spawn';


/**
 * @type {Object}
 */
export  const creator_meta = packageOf( currentModulePath() );


/**
 * @param {String} path
 *
 * @return {String}
 */
export  function packageNameOf(path) {

    return  basename( resolve( path ) ).toLowerCase().replace(/[^@\w]+/g, '-');
}


/**
 * @param {String}   command
 * @param {String[]} [args]
 * @param {Object}   [options]
 *
 * @return {Buffer|String}
 *
 * @see https://nodejs.org/dist/latest-v6.x/docs/api/child_process.html#child_process_child_process_spawnsync_command_args_options
 */
export  function spawnSync(command, args, options) {

    const result = spawn.sync(command, args, options);

    if ( result.status )  throw result.error;

    return result.stdout;
}


/**
 * @param {String}     path     - Local folder
 * @param {String|URL} [remote] - Git URL of a Remote repository
 *
 * @return {SimpleGit}
 */
export  async function bootGit(path, remote) {

    ensureDirSync( path );

    const git = Git( path );

    if (! (await git.checkIsRepo()))  await git.init();

    if (! (await git.getRemotes())[0]) {

        if (! remote) {

            const package_name = packageNameOf( path ),
                userID = await git.raw(['config', '--get', 'user.name']);

            remote = `https://github.com/${userID.trim()}/${package_name}`;
        }

        await git.addRemote('origin', remote);
    }

    return git;
}


/**
 * @param {String}   template - Path relative from this package
 * @param {String}   dist     - Path relative from `process.cwd()`
 * @param {Function} [filter]
 */
export  async function copyFrom(template, dist, filter) {

    template = join(creator_meta.path, template);

    await copy(template,  dist,  {overwrite: false, filter});

    const setting = readdirSync( template )
        .filter(file  =>  extname(file) === '.json');

    for (let file of setting) {

        const source = join(template, file), target = join(dist, file);

        await outputJSON(
            target,  patch(await readJSON( target ),  await readJSON( source ))
        );
    }
}


/**
 * @param {String|URL} URI       - Git URL
 * @param {String}     [path=''] - Copy to the path
 * @param {String}     [cwd='.']
 */
export  async function copyFromGit(URI,  path = '',  cwd = '.') {

    spawnSync('git',  ['clone', URI , path],  {stdio: 'inherit', cwd});

    await remove( join(path, '.git/') );
}


/**
 * @param {String}    path - Project root
 * @param {SimpleGit} git  - Git repository instance of `path`
 */
export  async function setRoot(path, git) {

    await copyFrom('./template', path);

    if (! findFile(/ReadMe(\.(md|markdown))?/i, path))
        await outputFile(
            join(path, 'ReadMe.md'),
            `# ${packageNameOf( path )}

Web-site generated by [${creator_meta.meta.name}](${creator_meta.meta.homepage})`
        );

    const config = join(path, 'package.json');

    const meta = await readJSON( config );

    meta.author = (await git.raw(['config', '--get', 'user.email'])).trim();

    await outputJSON(config, meta);
}


var index = 0;
/**
 * @param {String}                                                  title
 * @param {function(index: Number, title: String, end: Boolean): *} logic
 * @param {Boolean}                                                 [end] - `true` to reset index
 *
 * @return {*} Data returned by `logic`
 */
export  function step(title, logic, end) {

    title = ` ${++index}. ${title}`;

    console.info(`\n${title}\n ${'-'.repeat(title.length - 1)}`);

    logic = logic(index, title, end);

    if ( end )  index = 0;

    return logic;
}
